version: '2.2'
services:
  node:
    image: "node:10.13-alpine"
    container_name: docker-basior_scrum_poker-node
    restart: always
    user: "node"
    working_dir: /usr/app
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - BASIOR_SCRUM_POKER__MONGO_HOST=docker-basior_scrum_poker-mongo
      - BASIOR_SCRUM_POKER__MONGO_USER=root
      - BASIOR_SCRUM_POKER__MONGO_PASS=example
  mongo:
    image: mongo:latest
    container_name: docker-basior_scrum_poker-mongo
    restart: always
    ports:
      - 27017:27017
  apache:
    image: webdevops/apache:latest
    container_name: docker-basior_scrum_poker-apache
    restart: always
    ports:
        - 8080:80
        - 443:443
    volumes:
      - ./Webapp/dist:/app
      - ./docker/apache/app.conf:/opt/docker/etc/httpd/conf.d/11-app.conf