export default {
    ACTION_PREVIEW_ROOM_BY_ID: 'ACTION_PREVIEW_ROOM_BY_ID',
    ACTION_PREVIEW_ROOM_BY_NAME_AND_PASSWORD: 'ACTION_PREVIEW_ROOM_BY_NAME_AND_PASSWORD',

    EVENT_FOUND_ROOM_ID_FOR_PREVIEW: 'EVENT_FOUND_ROOM_ID_FOR_PREVIEW',
    EVENT_CHANGE_PREVIEW_ROOM_DETAILS: 'EVENT_CHANGE_PREVIEW_ROOM_DETAILS',
    EVENT_PREVIEW_ROOM_CONNECTED: 'EVENT_PREVIEW_ROOM_CONNECTED',
    EVENT_PREVIEW_ROOM_NOT_FOUND: 'EVENT_PREVIEW_ROOM_NOT_FOUND'
};