export default {
    ACTION_EMIT: 'ACTION_EMIT',
    ACTION_EMIT_REGISTER_USER: 'ACTION_EMIT_REGISTER_USER',
    ACTION_EMIT_REGISTER_USER_BY_ID: 'ACTION_EMIT_REGISTER_USER_BY_ID',
    ACTION_EMIT_CREATE_NEW_ROOM: 'ACTION_EMIT_CREATE_NEW_ROOM',
    ACTION_EMIT_JOIN_ROOM_BY_NAME: 'ACTION_EMIT_JOIN_ROOM_BY_NAME',
    ACTION_EMIT_JOIN_ROOM_BY_ID: 'ACTION_EMIT_JOIN_ROOM_BY_ID',
    ACTION_EMIT_FORGET_ABOUT_LAST_VISITED_ROOM: 'ACTION_EMIT_FORGET_ABOUT_LAST_VISITED_ROOM',
};