export default {
    ACTION_REGISTER_NEW_USER: 'ACTION_REGISTER_NEW_USER',
    ACTION_REGISTER_USER_BY_ID: 'ACTION_REGISTER_USER_BY_ID',
    ACTION_REGISTER_USER_BY_NAME_AND_PASSWORD: 'ACTION_REGISTER_USER_BY_NAME_AND_PASSWORD',
    ACTION_CLEAR_USER_DETAILS: 'ACTION_CLEAR_USER_DETAILS',

    ACTION_FORGET_ABOUT_LAST_VISITED_ROOM: 'ACTION_FORGET_ABOUT_LAST_VISITED_ROOM',
    ACTION_REQUEST_USER_DETAILS: 'ACTION_REQUEST_USER_DETAILS',

    EVENT_USER_NOT_FOUND: 'EVENT_USER_NOT_FOUND',
    EVENT_CHANGE_SAVED: 'EVENT_CHANGE_SAVED',
    EVENT_USER_REGISTERED: 'EVENT_USER_REGISTERED',
    EVENT_USER_CHANGED_REGISTER_STATUS: 'EVENT_USER_CHANGED_REGISTER_STATUS',
    EVENT_USER_REGISTER_FAIL: 'EVENT_USER_REGISTER_FAIL',
    EVENT_USER_DETAILS: 'EVENT_USER_DETAILS',
    EVENT_REGISTER_USER_ALREADY_EXISTS: 'EVENT_REGISTER_USER_ALREADY_EXISTS'
};